### ISSUE TITLE
对于文言文似乎有些丢失

### ISSUE THREAD

**Issue by ghost** [palp1tate/fetch-gushiwen#1]
https://so.gushiwen.cn/search.aspx?value=%E5%B2%B3%E9%98%B3%E6%A5%BC%E8%AE%B0&valuej=%E5%B2%B3
如这篇，会丢失注释，并且相对于普通诗歌，文言文似乎多一些卡片板块，语法分析之类

**Comment by palp1tate** [comment]
@TimeTraveller-ZEN 感谢你的issue，最新版本参见：https://github.com/palp1tate/fetch-gushiwen/releases/tag/v1.0.0
已支持批量爬取文言文：
![image](https://github.com/palp1tate/fetch-gushiwen/assets/120303802/f64be601-c200-48f3-9b53-8053d6da9e47)
同时已修复部分文言文有译文和注释但爬取结果缺失的问题，另外文言文多一些卡片板块，这个确实，但我这边暂时不准备继续加入这些新内容了，sorry，如果你有兴趣的话，欢迎提pr
同时最新版本支持爬取单个诗歌，以及写入单个诗歌的数据到csv，在新增的两个py里

**Comment by palp1tate** [comment]
> https://so.gushiwen.cn/search.aspx?value=%E5%B2%B3%E9%98%B3%E6%A5%BC%E8%AE%B0&valuej=%E5%B2%B3 如这篇，会丢失注释，并且相对于普通诗歌，文言文似乎多一些卡片板块，语法分析之类

https://github.com/palp1tate/fetch-gushiwen/releases/tag/v1.1.1
这个版本适配所有文言文

**Comment by ghost** [comment]
谢谢谢谢，辛苦了！

**Comment by ghost** [comment]
按照板块提取内容确实更条理和合理，可能会有些罕见板块卡片会遗漏，有没有一个额外“原始未处理内容”的列，储存当前页面所有html的内容（当然全部都展开后的），这样就当个备份，确保穷尽所有内容，防止古诗文网有一天不能爬取或者关站。当然这个可能有点强迫症感觉哈哈

**Comment by palp1tate** [comment]
> 按照板块提取内容确实更条理和合理，可能会有些罕见板块卡片会遗漏，有没有一个额外“原始未处理内容”的列，储存当前页面所有html的内容（当然全部都展开后的），这样就当个备份，确保穷尽所有内容，防止古诗文网有一天不能爬取或者关站。当然这个可能有点强迫症感觉哈哈

Sounds great.You can have a try.
